# Generated by Django 6.0.5 on 2026-05-08 18:54

from django.db import migrations

DEFAULT_CATEGORIES = [
    ('Breakfast', 'Morning meals and breakfast recipes'),
    ('Lunch', 'Midday meals and lunch recipes'),
    ('Dinner', 'Evening meals and dinner recipes'),
    ('Dessert', 'Sweet treats and dessert recipes'),
]


def add_categories(apps, schema_editor):
    Category = apps.get_model('main', 'Category')
    for name, description in DEFAULT_CATEGORIES:
        Category.objects.get_or_create(name=name, defaults={'description': description})


def remove_categories(apps, schema_editor):
    Category = apps.get_model('main', 'Category')
    names = [name for name, _ in DEFAULT_CATEGORIES]
    Category.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_created_at_favourite_added_at_and_more'),
    ]

    operations = [
        migrations.RunPython(add_categories, remove_categories),
    ]
