# Generated by Django 6.0.5 on 2026-05-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
    ]
